text = input("Enter text to write to the file: ")
f = open("output.txt", "w")
f.write(text + "\n")
f.close()
print("Data written to optput.txt")
more = input("Enter additional text to append: ")
f = open("output.txt", "a")
f.write(more + "\n")
f.close()
print("Data appended.")
f = open("output.txt", "r")
print("\nFinal content of output.txt:")
print(f.read())
f.close()
